# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/common.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("api/v1/common.proto", :syntax => :proto3) do
    add_message "github.com.tinkerbell.pbnj.api.v1.Host" do
      optional :host, :string, 1
    end
    add_message "github.com.tinkerbell.pbnj.api.v1.ExternalAuthn" do
      optional :host, :message, 1, "github.com.tinkerbell.pbnj.api.v1.Host"
    end
    add_message "github.com.tinkerbell.pbnj.api.v1.DirectAuthn" do
      optional :host, :message, 1, "github.com.tinkerbell.pbnj.api.v1.Host"
      optional :username, :string, 2
      optional :password, :string, 3
    end
    add_message "github.com.tinkerbell.pbnj.api.v1.Authn" do
      oneof :authn do
        optional :directAuthn, :message, 1, "github.com.tinkerbell.pbnj.api.v1.DirectAuthn"
      end
    end
    add_message "github.com.tinkerbell.pbnj.api.v1.Vendor" do
      optional :name, :string, 1
    end
    add_enum "github.com.tinkerbell.pbnj.api.v1.Code" do
      value :OK, 0
      value :CANCELLED, 1
      value :UNKNOWN, 2
      value :INVALID_ARGUMENT, 3
      value :DEADLINE_EXCEEDED, 4
      value :NOT_FOUND, 5
      value :ALREADY_EXISTS, 6
      value :PERMISSION_DENIED, 7
      value :UNAUTHENTICATED, 16
      value :RESOURCE_EXHAUSTED, 8
      value :FAILED_PRECONDITION, 9
      value :ABORTED, 10
      value :OUT_OF_RANGE, 11
      value :UNIMPLEMENTED, 12
      value :INTERNAL, 13
      value :UNAVAILABLE, 14
      value :DATA_LOSS, 15
    end
  end
end

module Pbnj
  module Api
    module V1
      Host = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.Host").msgclass
      ExternalAuthn = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.ExternalAuthn").msgclass
      DirectAuthn = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.DirectAuthn").msgclass
      Authn = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.Authn").msgclass
      Vendor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.Vendor").msgclass
      Code = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.Code").enummodule
    end
  end
end
