# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: api/v1/machine.proto for package 'Pbnj.Api.V1'

require 'grpc'
require 'api/v1/machine_pb'

module Pbnj
  module Api
    module V1
      module Machine
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'github.com.tinkerbell.pbnj.api.v1.Machine'

          rpc :BootDevice, ::Pbnj::Api::V1::DeviceRequest, ::Pbnj::Api::V1::DeviceResponse
          rpc :Power, ::Pbnj::Api::V1::PowerRequest, ::Pbnj::Api::V1::PowerResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
