# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/machine.proto

require 'google/protobuf'

require 'api/v1/common_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("api/v1/machine.proto", :syntax => :proto3) do
    add_message "github.com.tinkerbell.pbnj.api.v1.DeviceRequest" do
      optional :authn, :message, 1, "github.com.tinkerbell.pbnj.api.v1.Authn"
      optional :vendor, :message, 2, "github.com.tinkerbell.pbnj.api.v1.Vendor"
      optional :boot_device, :enum, 3, "github.com.tinkerbell.pbnj.api.v1.BootDevice"
      optional :persistent, :bool, 4
      optional :efi_boot, :bool, 5
    end
    add_message "github.com.tinkerbell.pbnj.api.v1.DeviceResponse" do
      optional :task_id, :string, 1
    end
    add_message "github.com.tinkerbell.pbnj.api.v1.PowerRequest" do
      optional :authn, :message, 1, "github.com.tinkerbell.pbnj.api.v1.Authn"
      optional :vendor, :message, 2, "github.com.tinkerbell.pbnj.api.v1.Vendor"
      optional :power_action, :enum, 3, "github.com.tinkerbell.pbnj.api.v1.PowerAction"
      optional :soft_timeout, :int32, 4
      optional :off_duration, :int32, 5
    end
    add_message "github.com.tinkerbell.pbnj.api.v1.PowerResponse" do
      optional :task_id, :string, 1
    end
    add_enum "github.com.tinkerbell.pbnj.api.v1.BootDevice" do
      value :BOOT_DEVICE_UNSPECIFIED, 0
      value :BOOT_DEVICE_NONE, 1
      value :BOOT_DEVICE_BIOS, 2
      value :BOOT_DEVICE_CDROM, 4
      value :BOOT_DEVICE_DISK, 5
      value :BOOT_DEVICE_PXE, 6
    end
    add_enum "github.com.tinkerbell.pbnj.api.v1.PowerAction" do
      value :POWER_ACTION_UNSPECIFIED, 0
      value :POWER_ACTION_ON, 1
      value :POWER_ACTION_OFF, 2
      value :POWER_ACTION_HARDOFF, 3
      value :POWER_ACTION_CYCLE, 4
      value :POWER_ACTION_RESET, 5
      value :POWER_ACTION_STATUS, 6
    end
  end
end

module Pbnj
  module Api
    module V1
      DeviceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.DeviceRequest").msgclass
      DeviceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.DeviceResponse").msgclass
      PowerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.PowerRequest").msgclass
      PowerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.PowerResponse").msgclass
      BootDevice = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.BootDevice").enummodule
      PowerAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.PowerAction").enummodule
    end
  end
end
