# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/task.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("api/v1/task.proto", :syntax => :proto3) do
    add_message "github.com.tinkerbell.pbnj.api.v1.StatusRequest" do
      optional :task_id, :string, 1
    end
    add_message "github.com.tinkerbell.pbnj.api.v1.StatusResponse" do
      optional :id, :string, 1
      optional :description, :string, 2
      optional :error, :message, 3, "github.com.tinkerbell.pbnj.api.v1.Error"
      optional :state, :string, 4
      optional :result, :string, 5
      optional :complete, :bool, 6
      repeated :messages, :string, 7
    end
    add_message "github.com.tinkerbell.pbnj.api.v1.Error" do
      optional :code, :int32, 1
      optional :message, :string, 2
      repeated :details, :string, 3
    end
  end
end

module Pbnj
  module Api
    module V1
      StatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.StatusRequest").msgclass
      StatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.StatusResponse").msgclass
      Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.com.tinkerbell.pbnj.api.v1.Error").msgclass
    end
  end
end
